### ISSUE TITLE
[Refactor] Prep for milestone 1

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#125]
- [x] manually merge #123 
- [x] connect source filter
- [ ] connect  time filter
- [ ] go through comments for #124  and #130
- [ ] add ping to mock server on app reload  
- [ ] What should we display on home page?
